USE MASTER
GO

IF EXISTS(SELECT 1 FROM SYS.DATABASES WHERE NAME = 'GESTAO_CLIENTE')
BEGIN
	DROP DATABASE GESTAO_CLIENTE

	PRINT('BASE GESTAO_CLIENTE APAGADA COM SUCESSO!')
END

CREATE DATABASE GESTAO_CLIENTE
PRINT('BASE GESTAO_CLIENTE CRIADA COM SUCESSO!')
GO

USE GESTAO_CLIENTE
GO

DROP TABLE IF EXISTS TB_CLIENTE
DROP TABLE IF EXISTS TB_SITUACAO_CLIENTE




CREATE TABLE TB_SITUACAO_CLIENTE
(
	CD_SITUACAO_CLIENTE INT IDENTITY NOT NULL PRIMARY KEY,
	DC_SITUACAO VARCHAR(200) UNIQUE,
	DT_ALTERACAO DATETIME
)
PRINT('TABELA TB_SITUACAO_CLIENTE CRIADA COM SUCESSO!')

CREATE TABLE TB_CLIENTE
(
	CD_CLIENTE INT IDENTITY NOT NULL PRIMARY KEY,
	NM_CLIENTE VARCHAR(200) NOT NULL,
	NR_CPF BIGINT UNIQUE NOT NULL,
	DC_SEXO VARCHAR(3) NOT NULL,
	DT_NASCIMENTO VARCHAR(10),
	CD_SITUACAO_CLIENTE INT REFERENCES TB_SITUACAO_CLIENTE(CD_SITUACAO_CLIENTE),
	DT_ALTERACAO DATETIME
)
PRINT('TABELA TB_CLIENTE CRIADA COM SUCESSO!')
GO





--=======================================APLICAÇÃO DE PROCEDURES=============================================

IF OBJECTPROPERTY(object_id('dbo.SPS_CLIENTE'), N'IsProcedure') = 1
BEGIN
	DROP PROCEDURE dbo.SPS_CLIENTE
	PRINT '** A PROC SPS_CLIENTE FOI APAGADA COM SUCESSO **'
END
GO
CREATE PROCEDURE dbo.SPS_CLIENTE
(
	@CD_CLIENTE INT = NULL,
	@NM_CLIENTE VARCHAR(200) = NULL,
	@NR_CPF BIGINT = NULL,
	@DC_SEXO VARCHAR(3) = NULL,
	@CD_SITUACAO_CLIENTE INT = NULL
)
AS
BEGIN
	SET NOCOUNT ON
----------------------
	
	DECLARE @SQL VARCHAR(MAX)


	SET @SQL = 'SELECT A.CD_CLIENTE,
					   A.NM_CLIENTE,
					   A.NR_CPF,
					   A.DC_SEXO,
					   A.DT_NASCIMENTO,
					   B.CD_SITUACAO_CLIENTE,
					   B.DC_SITUACAO,
					   A.DT_ALTERACAO 
	              FROM TB_CLIENTE A
				  JOIN TB_SITUACAO_CLIENTE B
				    ON A.CD_SITUACAO_CLIENTE = B.CD_SITUACAO_CLIENTE
				 WHERE 1=1
				 '


	--ADICIONA O FILTRO SE A VARIAVEL NAO ESTIVER NULA
	IF (@CD_CLIENTE IS NOT NULL)
	BEGIN
		SET @SQL = @SQL + 'AND CD_CLIENTE = '+CONVERT(VARCHAR(40),@CD_CLIENTE)+' '
	END

	IF (@NM_CLIENTE IS NOT NULL)
	BEGIN
		SET @SQL = @SQL + 'AND NM_CLIENTE LIKE (''%'+@NM_CLIENTE+'%'') '
	END

	IF (@NR_CPF IS NOT NULL)
	BEGIN
		SET @SQL = @SQL + 'AND NR_CPF = '+@NR_CPF+' '
	END

	IF (@DC_SEXO IS NOT NULL)
	BEGIN
		SET @SQL = @SQL + 'AND DC_SEXO = '+@DC_SEXO+' '
	END


	IF (@CD_SITUACAO_CLIENTE IS NOT NULL)
	BEGIN
		SET @SQL = @SQL + 'AND B.CD_SITUACAO_CLIENTE = '+CONVERT(VARCHAR(40),@CD_SITUACAO_CLIENTE)+' '
	END

	--EXECUTA A QUERY CRIADA DINAMCIAMENTE
	EXEC (@SQL)
----------------------
END
GO
IF OBJECTPROPERTY(object_id('dbo.SPS_CLIENTE'), N'IsProcedure') = 1
BEGIN
	PRINT '** A PROC SPS_CLIENTE FOI CRIADA COM SUCESSO **'
END
GO


IF OBJECTPROPERTY(object_id('dbo.SPI_CLIENTE'), N'IsProcedure') = 1
BEGIN
	DROP PROCEDURE dbo.SPI_CLIENTE
	PRINT '** A PROC SPI_CLIENTE FOI APAGADA COM SUCESSO **'
END
GO
CREATE PROCEDURE dbo.SPI_CLIENTE
(
	@NM_CLIENTE VARCHAR(200),
	@NR_CPF BIGINT,
	@DC_SEXO VARCHAR(3),
	@DT_NASCIMENTO DATE,
	@CD_SITUACAO_CLIENTE INT
)
AS
BEGIN
	SET NOCOUNT ON
----------------------


	IF EXISTS(SELECT TOP 1 * FROM TB_CLIENTE WHERE NR_CPF = @NR_CPF)
	BEGIN
		RAISERROR ('O CPF informado ja está cadastrado.', 16, 1)
		return
	END

	INSERT INTO TB_CLIENTE 
				(
				  NM_CLIENTE,
				  NR_CPF,
				  DC_SEXO,
				  DT_NASCIMENTO,
				  CD_SITUACAO_CLIENTE,
				  DT_ALTERACAO
				)
		 VALUES (
				  @NM_CLIENTE,
				  @NR_CPF,
				  @DC_SEXO,
				  @DT_NASCIMENTO,
				  @CD_SITUACAO_CLIENTE,
				  GETDATE()
				)

----------------------
END
GO
IF OBJECTPROPERTY(object_id('dbo.SPI_CLIENTE'), N'IsProcedure') = 1
BEGIN
	PRINT '** A PROC SPI_CLIENTE FOI CRIADA COM SUCESSO **'
END
GO


IF OBJECTPROPERTY(object_id('dbo.SPU_CLIENTE'), N'IsProcedure') = 1
BEGIN
	DROP PROCEDURE dbo.SPU_CLIENTE
	PRINT '** A PROC SPU_CLIENTE FOI APAGADA COM SUCESSO **'
END
GO
CREATE PROCEDURE dbo.SPU_CLIENTE
(
	@CD_CLIENTE INT,
	@NM_CLIENTE VARCHAR(200),
	@NR_CPF BIGINT,
	@DC_SEXO VARCHAR(3),
	@DT_NASCIMENTO DATE,
	@CD_SITUACAO_CLIENTE INT
)
AS
BEGIN
	SET NOCOUNT ON
----------------------

	IF EXISTS(SELECT TOP 1 * FROM TB_CLIENTE WHERE NR_CPF = @NR_CPF AND CD_CLIENTE <> @CD_CLIENTE)
	BEGIN
		RAISERROR ('O CPF informado ja está cadastrado.', 16, 1)
		return
	END

	UPDATE TB_CLIENTE SET NM_CLIENTE = @NM_CLIENTE,
						  NR_CPF = @NR_CPF,
						  DC_SEXO = @DC_SEXO,
						  DT_NASCIMENTO = @DT_NASCIMENTO,
						  CD_SITUACAO_CLIENTE = @CD_SITUACAO_CLIENTE,
						  DT_ALTERACAO = GETDATE()

	 WHERE CD_CLIENTE = @CD_CLIENTE

----------------------
END
GO
IF OBJECTPROPERTY(object_id('dbo.SPU_CLIENTE'), N'IsProcedure') = 1
BEGIN
	PRINT '** A PROC SPU_CLIENTE FOI CRIADA COM SUCESSO **'
END
GO


IF OBJECTPROPERTY(object_id('dbo.SPD_CLIENTE'), N'IsProcedure') = 1
BEGIN
	DROP PROCEDURE dbo.SPD_CLIENTE
	PRINT '** A PROC SPD_CLIENTE FOI APAGADA COM SUCESSO **'
END
GO
CREATE PROCEDURE dbo.SPD_CLIENTE
(
	@CD_CLIENTE INT
)
AS
BEGIN
	SET NOCOUNT ON
----------------------

	DELETE TB_CLIENTE WHERE CD_CLIENTE = @CD_CLIENTE

----------------------
END
GO
IF OBJECTPROPERTY(object_id('dbo.SPD_CLIENTE'), N'IsProcedure') = 1
BEGIN
	PRINT '** A PROC SPD_CLIENTE FOI CRIADA COM SUCESSO **'
END
GO

IF OBJECTPROPERTY(object_id('dbo.SPS_SITUACAO'), N'IsProcedure') = 1
BEGIN
	DROP PROCEDURE dbo.SPS_SITUACAO
	PRINT '** A PROC SPS_SITUACAO FOI APAGADA COM SUCESSO **'
END
GO
CREATE PROCEDURE dbo.SPS_SITUACAO
(
	@CD_SITUACAO_CLIENTE INT = NULL,
	@DC_SITUACAO VARCHAR(200) = NULL
)
AS
BEGIN
	SET NOCOUNT ON
----------------------
	
	DECLARE @SQL VARCHAR(MAX)


	SET @SQL = 'SELECT CD_SITUACAO_CLIENTE,
					   DC_SITUACAO,
					   DT_ALTERACAO
	              FROM TB_SITUACAO_CLIENTE
				 WHERE 1=1
				 '


	--ADICIONA O FILTRO SE A VARIAVEL NAO ESTIVER NULA
	IF (@CD_SITUACAO_CLIENTE IS NOT NULL)
	BEGIN
		SET @SQL = @SQL + 'AND CD_SITUACAO_CLIENTE = '+CONVERT(VARCHAR(40),@CD_SITUACAO_CLIENTE)+' '
	END

	IF (@DC_SITUACAO IS NOT NULL)
	BEGIN
		SET @SQL = @SQL + 'AND DC_SITUACAO LIKE (''%'+@DC_SITUACAO+'%'') '
	END


	--EXECUTA A QUERY CRIADA DINAMCIAMENTE
	EXEC (@SQL)
----------------------
END
GO
IF OBJECTPROPERTY(object_id('dbo.SPS_SITUACAO'), N'IsProcedure') = 1
BEGIN
	PRINT '** A PROC SPS_SITUACAO FOI CRIADA COM SUCESSO **'
END
GO


IF OBJECTPROPERTY(object_id('dbo.SPI_SITUACAO'), N'IsProcedure') = 1
BEGIN
	DROP PROCEDURE dbo.SPI_SITUACAO
	PRINT '** A PROC SPI_SITUACAO FOI APAGADA COM SUCESSO **'
END
GO
CREATE PROCEDURE dbo.SPI_SITUACAO
(
	@DC_SITUACAO VARCHAR(200)
)
AS
BEGIN
	SET NOCOUNT ON
----------------------


	IF EXISTS(SELECT TOP 1 * FROM TB_SITUACAO_CLIENTE WHERE DC_SITUACAO = @DC_SITUACAO)
	BEGIN
		RAISERROR ('A Situação informada ja está cadastrada.', 16, 1)
		return
	END

	INSERT INTO TB_SITUACAO_CLIENTE 
				(
				  DC_SITUACAO,
				  DT_ALTERACAO
				)
		 VALUES (
				  @DC_SITUACAO,
				  GETDATE()
				)

----------------------
END
GO
IF OBJECTPROPERTY(object_id('dbo.SPI_SITUACAO'), N'IsProcedure') = 1
BEGIN
	PRINT '** A PROC SPI_SITUACAO FOI CRIADA COM SUCESSO **'
END
GO


IF OBJECTPROPERTY(object_id('dbo.SPU_SITUACAO'), N'IsProcedure') = 1
BEGIN
	DROP PROCEDURE dbo.SPU_SITUACAO
	PRINT '** A PROC SPU_SITUACAO FOI APAGADA COM SUCESSO **'
END
GO
CREATE PROCEDURE dbo.SPU_SITUACAO
(	
	@CD_SITUACAO_CLIENTE INT,
	@DC_SITUACAO VARCHAR(200)
)
AS
BEGIN
	SET NOCOUNT ON
----------------------

	IF EXISTS(SELECT TOP 1 * FROM TB_SITUACAO_CLIENTE WHERE DC_SITUACAO = @DC_SITUACAO AND CD_SITUACAO_CLIENTE <> @CD_SITUACAO_CLIENTE)
	BEGIN
		RAISERROR ('A Situação informada ja está cadastrada.', 16, 1)
		return
	END

	UPDATE TB_SITUACAO_CLIENTE SET DC_SITUACAO = @DC_SITUACAO,
								   DT_ALTERACAO = GETDATE()

	 WHERE CD_SITUACAO_CLIENTE = @CD_SITUACAO_CLIENTE

----------------------
END
GO
IF OBJECTPROPERTY(object_id('dbo.SPU_SITUACAO'), N'IsProcedure') = 1
BEGIN
	PRINT '** A PROC SPU_SITUACAO FOI CRIADA COM SUCESSO **'
END
GO


IF OBJECTPROPERTY(object_id('dbo.SPD_SITUACAO'), N'IsProcedure') = 1
BEGIN
	DROP PROCEDURE dbo.SPD_SITUACAO
	PRINT '** A PROC SPD_SITUACAO FOI APAGADA COM SUCESSO **'
END
GO
CREATE PROCEDURE dbo.SPD_SITUACAO
(
	@CD_SITUACAO_CLIENTE INT	
)
AS
BEGIN
	SET NOCOUNT ON
----------------------

	IF EXISTS(SELECT TOP 1 * FROM TB_CLIENTE WHERE CD_SITUACAO_CLIENTE = @CD_SITUACAO_CLIENTE)
	BEGIN
		RAISERROR ('Não é possível excluir, pois há clientes que utilizam este dado.', 16, 1)
		return
	END


	DELETE TB_SITUACAO_CLIENTE WHERE CD_SITUACAO_CLIENTE = @CD_SITUACAO_CLIENTE

----------------------
END
GO
IF OBJECTPROPERTY(object_id('dbo.SPD_SITUACAO'), N'IsProcedure') = 1
BEGIN
	PRINT '** A PROC SPD_SITUACAO FOI CRIADA COM SUCESSO **'
END
GO