USE GESTAO_CLIENTE
GO

IF OBJECTPROPERTY(object_id('dbo.SPD_SITUACAO'), N'IsProcedure') = 1
BEGIN
	DROP PROCEDURE dbo.SPD_SITUACAO
	PRINT '** A PROC SPD_SITUACAO FOI APAGADA COM SUCESSO **'
END
GO
CREATE PROCEDURE dbo.SPD_SITUACAO
(
	@CD_SITUACAO_CLIENTE INT	
)
AS
BEGIN
	SET NOCOUNT ON
----------------------

	IF EXISTS(SELECT TOP 1 * FROM TB_CLIENTE WHERE CD_SITUACAO_CLIENTE = @CD_SITUACAO_CLIENTE)
	BEGIN
		RAISERROR ('Não é possível excluir, pois há clientes que utilizam este dado.', 16, 1)
		return
	END


	DELETE TB_SITUACAO_CLIENTE WHERE CD_SITUACAO_CLIENTE = @CD_SITUACAO_CLIENTE

----------------------
END
GO
IF OBJECTPROPERTY(object_id('dbo.SPD_SITUACAO'), N'IsProcedure') = 1
BEGIN
	PRINT '** A PROC SPD_SITUACAO FOI CRIADA COM SUCESSO **'
END
GO