USE GESTAO_CLIENTE
GO

IF OBJECTPROPERTY(object_id('dbo.SPI_CLIENTE'), N'IsProcedure') = 1
BEGIN
	DROP PROCEDURE dbo.SPI_CLIENTE
	PRINT '** A PROC SPI_CLIENTE FOI APAGADA COM SUCESSO **'
END
GO
CREATE PROCEDURE dbo.SPI_CLIENTE
(
	@NM_CLIENTE VARCHAR(200),
	@NR_CPF BIGINT,
	@DC_SEXO VARCHAR(3),
	@DT_NASCIMENTO DATE,
	@CD_SITUACAO_CLIENTE INT
)
AS
BEGIN
	SET NOCOUNT ON
----------------------


	IF EXISTS(SELECT TOP 1 * FROM TB_CLIENTE WHERE NR_CPF = @NR_CPF)
	BEGIN
		RAISERROR ('O CPF informado ja está cadastrado.', 16, 1)
		return
	END

	INSERT INTO TB_CLIENTE 
				(
				  NM_CLIENTE,
				  NR_CPF,
				  DC_SEXO,
				  DT_NASCIMENTO,
				  CD_SITUACAO_CLIENTE,
				  DT_ALTERACAO
				)
		 VALUES (
				  @NM_CLIENTE,
				  @NR_CPF,
				  @DC_SEXO,
				  @DT_NASCIMENTO,
				  @CD_SITUACAO_CLIENTE,
				  GETDATE()
				)

----------------------
END
GO
IF OBJECTPROPERTY(object_id('dbo.SPI_CLIENTE'), N'IsProcedure') = 1
BEGIN
	PRINT '** A PROC SPI_CLIENTE FOI CRIADA COM SUCESSO **'
END
GO