USE GESTAO_CLIENTE
GO

IF OBJECTPROPERTY(object_id('dbo.SPS_SITUACAO'), N'IsProcedure') = 1
BEGIN
	DROP PROCEDURE dbo.SPS_SITUACAO
	PRINT '** A PROC SPS_SITUACAO FOI APAGADA COM SUCESSO **'
END
GO
CREATE PROCEDURE dbo.SPS_SITUACAO
(
	@CD_SITUACAO_CLIENTE INT = NULL,
	@DC_SITUACAO VARCHAR(200) = NULL
)
AS
BEGIN
	SET NOCOUNT ON
----------------------
	
	DECLARE @SQL VARCHAR(MAX)


	SET @SQL = 'SELECT CD_SITUACAO_CLIENTE,
					   DC_SITUACAO,
					   DT_ALTERACAO
	              FROM TB_SITUACAO_CLIENTE
				 WHERE 1=1
				 '


	--ADICIONA O FILTRO SE A VARIAVEL NAO ESTIVER NULA
	IF (@CD_SITUACAO_CLIENTE IS NOT NULL)
	BEGIN
		SET @SQL = @SQL + 'AND CD_SITUACAO_CLIENTE = '+CONVERT(VARCHAR(40),@CD_SITUACAO_CLIENTE)+' '
	END

	IF (@DC_SITUACAO IS NOT NULL)
	BEGIN
		SET @SQL = @SQL + 'AND DC_SITUACAO LIKE (''%'+@DC_SITUACAO+'%'') '
	END


	--EXECUTA A QUERY CRIADA DINAMCIAMENTE
	EXEC (@SQL)
----------------------
END
GO
IF OBJECTPROPERTY(object_id('dbo.SPS_SITUACAO'), N'IsProcedure') = 1
BEGIN
	PRINT '** A PROC SPS_SITUACAO FOI CRIADA COM SUCESSO **'
END
GO